// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**
	 *  Open a Git repository at the specified path.
	 * 
	 *  Validates the path exists and is a git repository,
	 *  then stores it as the current active repository.
	 *  Also starts a file watcher to detect external changes.
	 */
	openRepository: (path: string) => typedError<RepoStatus, GitError>(__TAURI_INVOKE("open_repository", { path })),
	/**
	 *  Get the current repository status.
	 * 
	 *  Returns branch name and dirty status for the currently open repository.
	 */
	getRepositoryStatus: () => typedError<RepoStatus, GitError>(__TAURI_INVOKE("get_repository_status")),
	/**
	 *  Check if a path is a valid Git repository.
	 * 
	 *  Used for drag-drop and "Open Repository" validation before attempting to open.
	 * 
	 *  Returns `Ok(false)` only when the folder genuinely holds no repository
	 *  (libgit2 `NotFound`). Any other failure — permission denied, libgit2
	 *  ownership validation ("dubious ownership"), corrupt metadata, ... — is a
	 *  real error: it is logged and returned as `Err` so the caller can tell the
	 *  user *why* the folder could not be opened instead of silently offering to
	 *  `git init` an existing repository.
	 */
	isGitRepository: (path: string) => typedError<boolean, GitError>(__TAURI_INVOKE("is_git_repository", { path })),
	/**
	 *  Close the current repository.
	 * 
	 *  Stops the file watcher and clears the stored repository path.
	 */
	closeRepository: () => typedError<null, GitError>(__TAURI_INVOKE("close_repository")),
	/**
	 *  Get the current staging status of the repository.
	 * 
	 *  Returns files grouped by staged (in index), unstaged (modified in workdir),
	 *  and untracked (new files not yet added).
	 */
	getStagingStatus: () => typedError<StagingStatus, GitError>(__TAURI_INVOKE("get_staging_status")),
	/**
	 *  Stage a single file for commit.
	 * 
	 *  The path must be relative to the repository root.
	 */
	stageFile: (path: string) => typedError<null, GitError>(__TAURI_INVOKE("stage_file", { path })),
	/**
	 *  Unstage a single file (remove from index, keep workdir changes).
	 * 
	 *  The path must be relative to the repository root.
	 */
	unstageFile: (path: string) => typedError<null, GitError>(__TAURI_INVOKE("unstage_file", { path })),
	/**
	 *  Stage multiple files for commit in a single operation.
	 * 
	 *  More efficient than calling stage_file repeatedly — performs a single index write.
	 *  Paths must be relative to the repository root.
	 */
	stageFiles: (paths: string[]) => typedError<null, GitError>(__TAURI_INVOKE("stage_files", { paths })),
	/**
	 *  Unstage multiple files (remove from index, keep workdir changes).
	 * 
	 *  More efficient than calling unstage_file repeatedly — performs a single reset.
	 *  Paths must be relative to the repository root.
	 */
	unstageFiles: (paths: string[]) => typedError<null, GitError>(__TAURI_INVOKE("unstage_files", { paths })),
	/**
	 *  Stage all changed files.
	 * 
	 *  Adds all modified, deleted, and new files to the index.
	 */
	stageAll: () => typedError<null, GitError>(__TAURI_INVOKE("stage_all")),
	/**
	 *  Unstage all staged files.
	 * 
	 *  Resets the index to match HEAD, keeping workdir changes.
	 */
	unstageAll: () => typedError<null, GitError>(__TAURI_INVOKE("unstage_all")),
	/**
	 *  Get the diff for a specific file.
	 * 
	 *  If `staged` is true, shows diff between HEAD and index.
	 *  If `staged` is false, shows diff between index and workdir.
	 */
	getFileDiff: (path: string, staged: boolean, contextLines: number) => typedError<FileDiff, GitError>(__TAURI_INVOKE("get_file_diff", { path, staged, contextLines })),
	/**
	 *  Get the diff for a specific file at a given commit.
	 * 
	 *  Shows the changes introduced by the commit (parent -> commit).
	 */
	getCommitFileDiff: (oid: string, path: string, contextLines: number) => typedError<FileDiff, GitError>(__TAURI_INVOKE("get_commit_file_diff", { oid, path, contextLines })),
	/**
	 *  Get a file's binary content as a base64 data URI from the working tree.
	 * 
	 *  Returns a data URI like `data:image/png;base64,...` for use in `<img>` tags.
	 */
	getFileBase64: (filePath: string) => typedError<string, GitError>(__TAURI_INVOKE("get_file_base64", { filePath })),
	/**
	 *  Get a file's binary content as a base64 data URI from a specific commit.
	 * 
	 *  Extracts the blob from the commit's tree and returns it as a data URI.
	 */
	getCommitFileBase64: (oid: string, filePath: string) => typedError<string, GitError>(__TAURI_INVOKE("get_commit_file_base64", { oid, filePath })),
	/**
	 *  Get per-line diff detail for a specific file.
	 * 
	 *  Returns enhanced hunk data with individual line information for interactive staging.
	 */
	getFileDiffHunks: (path: string, staged: boolean) => typedError<DiffHunkDetail[], GitError>(__TAURI_INVOKE("get_file_diff_hunks", { path, staged })),
	/**
	 *  Stage specific hunks of a file.
	 * 
	 *  Applies only the selected hunks from the workdir diff to the index,
	 *  leaving other hunks unstaged.
	 */
	stageHunks: (path: string, hunkIndices: number[]) => typedError<null, GitError>(__TAURI_INVOKE("stage_hunks", { path, hunkIndices })),
	/**
	 *  Unstage specific hunks of a file.
	 * 
	 *  Reverts the selected hunks from the index back to HEAD state,
	 *  keeping other staged hunks intact.
	 */
	unstageHunks: (path: string, hunkIndices: number[]) => typedError<null, GitError>(__TAURI_INVOKE("unstage_hunks", { path, hunkIndices })),
	/**
	 *  Stage specific lines within a hunk of a file.
	 * 
	 *  Lines are identified by their position in the diff. Only additions and deletions
	 *  within the specified line ranges are staged.
	 */
	stageLines: (path: string, hunkIndex: number, lineRanges: LineRange[]) => typedError<null, GitError>(__TAURI_INVOKE("stage_lines", { path, hunkIndex, lineRanges })),
	/**
	 *  Unstage specific lines within a hunk of a file.
	 * 
	 *  Reverts the selected lines from the index back to HEAD state,
	 *  keeping other staged lines intact.
	 */
	unstageLines: (path: string, hunkIndex: number, lineRanges: LineRange[]) => typedError<null, GitError>(__TAURI_INVOKE("unstage_lines", { path, hunkIndex, lineRanges })),
	/**
	 *  Create a new commit from staged changes.
	 * 
	 *  Creates a commit with the given message from the current index (staged changes).
	 *  If `amend` is true, replaces the last commit instead of creating a new one.
	 * 
	 *  # Errors
	 *  - `NoStagedChanges` if index is empty (nothing staged)
	 *  - `SignatureError` if git config lacks user.name/email
	 *  - Various git2 errors for other failures
	 */
	createCommit: (message: string, amend: boolean) => typedError<CommitInfo, GitError>(__TAURI_INVOKE("create_commit", { message, amend })),
	/**
	 *  Get the last commit message for amend pre-fill.
	 * 
	 *  Returns the HEAD commit's message parsed into subject and body components.
	 */
	getLastCommitMessage: () => typedError<LastCommitMessage, GitError>(__TAURI_INVOKE("get_last_commit_message")),
	/**
	 *  Get paginated commit history.
	 * 
	 *  Returns commits reachable from HEAD in `git log` order (children before
	 *  parents, newest first). Use skip and limit for pagination.
	 */
	getCommitHistory: (skip: number, limit: number) => typedError<CommitSummary[], GitError>(__TAURI_INVOKE("get_commit_history", { skip, limit })),
	/**  Get full details of a specific commit. */
	getCommitDetails: (oid: string) => typedError<CommitDetails, GitError>(__TAURI_INVOKE("get_commit_details", { oid })),
	/**
	 *  Search commits by message text.
	 *  Returns up to `limit` commits whose message contains `query` (case-insensitive).
	 */
	searchCommits: (query: string, limit: number) => typedError<CommitSummary[], GitError>(__TAURI_INVOKE("search_commits", { query, limit })),
	/**
	 *  IPC command to get the commit graph for visualization.
	 * 
	 *  # Arguments
	 *  * `limit` - Maximum number of commits to return (default: 100, max: 500)
	 *  * `offset` - Number of commits to skip (default: 0)
	 *  * `state` - Repository state containing the current repo path
	 * 
	 *  # Returns
	 *  A CommitGraph containing nodes and edges for visualization.
	 */
	getCommitGraph: (limit: number | null, offset: number | null) => typedError<CommitGraph, GitError>(__TAURI_INVOKE("get_commit_graph", { limit, offset })),
	/**  List all configured remotes for the current repository. */
	getRemotes: () => typedError<RemoteInfo[], GitError>(__TAURI_INVOKE("get_remotes")),
	/**
	 *  Fetch from a remote without merging.
	 * 
	 *  Downloads objects and refs from the remote but does not modify
	 *  the working directory or current branch.
	 */
	fetchFromRemote: (remote: string, onProgress: Channel<SyncProgress>) => typedError<SyncResult, GitError>(__TAURI_INVOKE("fetch_from_remote", { remote, onProgress })),
	/**
	 *  Push current branch to a remote.
	 * 
	 *  Sends local commits to the remote repository.
	 */
	pushToRemote: (remote: string, onProgress: Channel<SyncProgress>) => typedError<SyncResult, GitError>(__TAURI_INVOKE("push_to_remote", { remote, onProgress })),
	/**
	 *  Pull from a remote (fetch + merge).
	 * 
	 *  Downloads objects from the remote and merges the tracking branch
	 *  into the current branch. Fast-forward merges are preferred.
	 */
	pullFromRemote: (remote: string, onProgress: Channel<SyncProgress>) => typedError<SyncResult, GitError>(__TAURI_INVOKE("pull_from_remote", { remote, onProgress })),
	/**  List all local branches in the repository. */
	listBranches: () => typedError<BranchInfo[], GitError>(__TAURI_INVOKE("list_branches")),
	/**  Create a new branch from HEAD. */
	createBranch: (name: string, checkout: boolean) => typedError<BranchInfo, GitError>(__TAURI_INVOKE("create_branch", { name, checkout })),
	/**  Switch to an existing branch. */
	checkoutBranch: (branchName: string) => typedError<null, GitError>(__TAURI_INVOKE("checkout_branch", { branchName })),
	/**  Delete a local branch. */
	deleteBranch: (branchName: string, force: boolean) => typedError<null, GitError>(__TAURI_INVOKE("delete_branch", { branchName, force })),
	/**  List all branches (local and optionally remote) in the repository. */
	listAllBranches: (includeRemote: boolean) => typedError<BranchInfo[], GitError>(__TAURI_INVOKE("list_all_branches", { includeRemote })),
	/**  Checkout a remote branch by creating a local tracking branch. */
	checkoutRemoteBranch: (remoteBranch: string) => typedError<null, GitError>(__TAURI_INVOKE("checkout_remote_branch", { remoteBranch })),
	/**  Delete multiple local branches in a single batch operation. */
	batchDeleteBranches: (branchNames: string[], force: boolean) => typedError<BatchDeleteResult, GitError>(__TAURI_INVOKE("batch_delete_branches", { branchNames, force })),
	/**  Get recently checked-out branches from the HEAD reflog. */
	getRecentCheckouts: (limit: number | null) => typedError<RecentCheckout[], GitError>(__TAURI_INVOKE("get_recent_checkouts", { limit })),
	/**
	 *  Get ahead/behind counts for a local branch relative to its upstream.
	 * 
	 *  Returns `{ ahead: 0, behind: 0 }` when the branch has no upstream tracking branch.
	 */
	getBranchAheadBehind: (branchName: string) => typedError<AheadBehind, GitError>(__TAURI_INVOKE("get_branch_ahead_behind", { branchName })),
	/**  List all stash entries in the repository. */
	listStashes: () => typedError<StashEntry[], GitError>(__TAURI_INVOKE("list_stashes")),
	/**  Save current changes to stash. */
	stashSave: (message: string | null, includeUntracked: boolean) => typedError<string, GitError>(__TAURI_INVOKE("stash_save", { message, includeUntracked })),
	/**  Apply a stash by index without removing it. */
	stashApply: (index: number) => typedError<null, GitError>(__TAURI_INVOKE("stash_apply", { index })),
	/**  Apply a stash by index and remove it from the stash list. */
	stashPop: (index: number) => typedError<null, GitError>(__TAURI_INVOKE("stash_pop", { index })),
	/**  Drop a stash by index without applying it. */
	stashDrop: (index: number) => typedError<null, GitError>(__TAURI_INVOKE("stash_drop", { index })),
	/**  List all tags in the repository. */
	listTags: () => typedError<TagInfo[], GitError>(__TAURI_INVOKE("list_tags")),
	/**  Create a new tag. */
	createTag: (name: string, message: string | null, targetOid: string | null) => typedError<TagInfo, GitError>(__TAURI_INVOKE("create_tag", { name, message, targetOid })),
	/**  Delete a tag by name. */
	deleteTag: (name: string) => typedError<null, GitError>(__TAURI_INVOKE("delete_tag", { name })),
	/**  Merge a source branch into the current branch. */
	mergeBranch: (sourceBranch: string) => typedError<MergeResult, GitError>(__TAURI_INVOKE("merge_branch", { sourceBranch })),
	/**  Get the status of an in-progress merge. */
	getMergeStatus: () => typedError<MergeStatus, GitError>(__TAURI_INVOKE("get_merge_status")),
	/**  Abort an in-progress merge. */
	abortMerge: () => typedError<null, GitError>(__TAURI_INVOKE("abort_merge")),
	/**
	 *  List all conflicted file paths from the git index.
	 * 
	 *  Returns an empty Vec if no conflicts exist (not an error).
	 */
	listConflictFiles: () => typedError<string[], GitError>(__TAURI_INVOKE("list_conflict_files")),
	/**
	 *  Read ours/theirs/base content for a specific conflicted file from index stages.
	 * 
	 *  Uses git2 index stages (1=ancestor, 2=ours, 3=theirs) to read clean content
	 *  without conflict markers. Returns NotFound if the file is not in the conflict list.
	 */
	getConflictContent: (path: string) => typedError<ConflictContent, GitError>(__TAURI_INVOKE("get_conflict_content", { path })),
	/**
	 *  Write resolved content to a conflicted file, stage it, and clear the conflict.
	 * 
	 *  Writes the resolved content to the working directory file, then stages it
	 *  via `index.add_path()` which automatically clears the conflict entry.
	 */
	resolveConflictFile: (path: string, content: string) => typedError<null, GitError>(__TAURI_INVOKE("resolve_conflict_file", { path, content })),
	/**
	 *  Initialize Gitflow on the currently open repository.
	 * 
	 *  See [`init_gitflow_in_repo`] for the exact steps. Never discards local
	 *  changes: the switch to develop is a safe checkout.
	 */
	initGitflow: (config: GitflowConfig, pushDevelop: boolean) => typedError<GitflowInitResult, GitflowError>(__TAURI_INVOKE("init_gitflow", { config, pushDevelop })),
	/**  Start a new feature branch from develop. */
	startFeature: (name: string) => typedError<string, GitflowError>(__TAURI_INVOKE("start_feature", { name })),
	/**  Finish the current feature branch, merging to develop. */
	finishFeature: () => typedError<null, GitflowError>(__TAURI_INVOKE("finish_feature")),
	/**  Start a new release branch from develop. */
	startRelease: (version: string) => typedError<string, GitflowError>(__TAURI_INVOKE("start_release", { version })),
	/**
	 *  Finish the current release branch.
	 *  Merges to main AND develop, creates version tag, deletes branch.
	 */
	finishRelease: (tagMessage: string | null) => typedError<string, GitflowError>(__TAURI_INVOKE("finish_release", { tagMessage })),
	/**  Start a new hotfix branch from main. */
	startHotfix: (name: string) => typedError<string, GitflowError>(__TAURI_INVOKE("start_hotfix", { name })),
	/**
	 *  Finish the current hotfix branch.
	 *  Merges to main AND develop, creates tag, deletes branch.
	 */
	finishHotfix: (tagMessage: string | null) => typedError<string, GitflowError>(__TAURI_INVOKE("finish_hotfix", { tagMessage })),
	/**  Get current Gitflow status for UI. */
	getGitflowStatus: () => typedError<GitflowStatus, GitflowError>(__TAURI_INVOKE("get_gitflow_status")),
	/**  Abort current Gitflow operation, returning to source branch. */
	abortGitflow: () => typedError<null, GitflowError>(__TAURI_INVOKE("abort_gitflow")),
	/**
	 *  Validate a conventional commit message.
	 * 
	 *  Returns validation result with errors and warnings.
	 */
	validateConventionalCommit: (message: string) => __TAURI_INVOKE<ValidationResult>("validate_conventional_commit", { message }),
	/**
	 *  Suggest a commit type based on staged files.
	 * 
	 *  Analyzes the currently staged files and returns a type suggestion
	 *  with confidence level.
	 */
	suggestCommitType: () => typedError<TypeSuggestion, GitError>(__TAURI_INVOKE("suggest_commit_type")),
	/**
	 *  Get scope suggestions from commit history.
	 * 
	 *  Extracts scopes used in previous commits, sorted by frequency.
	 */
	getScopeSuggestions: (limit: number | null) => typedError<ScopeSuggestion[], GitError>(__TAURI_INVOKE("get_scope_suggestions", { limit })),
	/**  Infer scope from staged files based on common directory. */
	inferScopeFromStaged: () => typedError<string | null, GitError>(__TAURI_INVOKE("infer_scope_from_staged")),
	/**
	 *  Generate a changelog from commit history.
	 * 
	 *  Generates markdown changelog grouped by commit type.
	 */
	generateChangelogCmd: (fromRef: string | null, toRef: string | null, version: string | null) => typedError<ChangelogOutput, GitError>(__TAURI_INVOKE("generate_changelog_cmd", { fromRef, toRef, version })),
	/**  List all worktrees for the current repository. */
	listWorktrees: () => typedError<WorktreeInfo[], GitError>(__TAURI_INVOKE("list_worktrees")),
	/**  Create a new worktree. */
	createWorktree: (options: CreateWorktreeOptions) => typedError<WorktreeInfo, GitError>(__TAURI_INVOKE("create_worktree", { options })),
	/**  Delete a worktree. */
	deleteWorktree: (name: string, force: boolean, deleteBranch: boolean) => typedError<null, GitError>(__TAURI_INVOKE("delete_worktree", { name, force, deleteBranch })),
	/**
	 *  Get information about what can be undone.
	 *  Looks at HEAD reflog to find the previous state.
	 */
	getUndoInfo: () => typedError<UndoInfo, GitError>(__TAURI_INVOKE("get_undo_info")),
	/**  Undo the last operation by resetting HEAD to the previous reflog entry. */
	undoLastOperation: () => typedError<null, GitError>(__TAURI_INVOKE("undo_last_operation")),
	/**
	 *  Clone a Git repository with progress tracking.
	 * 
	 *  Clones a repository from a URL to a local destination path,
	 *  sending progress events through the provided channel.
	 * 
	 *  # Arguments
	 *  * `url` - The repository URL (HTTPS or SSH)
	 *  * `destination` - Local path where the repository will be cloned
	 *  * `on_progress` - Channel for sending progress events
	 * 
	 *  # Returns
	 *  The path to the cloned repository on success
	 */
	cloneRepository: (url: string, destination: string, onProgress: Channel<CloneProgress>) => typedError<string, GitError>(__TAURI_INVOKE("clone_repository", { url, destination, onProgress })),
	/**
	 *  Initialize a new Git repository at the specified path.
	 * 
	 *  Validates the path exists and is a directory that is not already a git repository,
	 *  then creates a new repository with an optional default branch name.
	 * 
	 *  # Arguments
	 *  * `path` - Directory where the repository will be initialized
	 *  * `default_branch` - Optional initial branch name (defaults to "main")
	 */
	gitInit: (path: string, defaultBranch: string | null) => typedError<InitResult, GitError>(__TAURI_INVOKE("git_init", { path, defaultBranch })),
	/**
	 *  List all available .gitignore template names.
	 * 
	 *  Attempts to fetch from GitHub API with a 5s timeout, falling back to
	 *  bundled templates on any error.
	 */
	listGitignoreTemplates: () => typedError<GitignoreTemplateList, GitError>(__TAURI_INVOKE("list_gitignore_templates")),
	/**
	 *  Get the content of a single .gitignore template by name.
	 * 
	 *  Tries GitHub API first, falls back to bundled templates.
	 */
	getGitignoreTemplate: (name: string) => typedError<GitignoreTemplate, GitError>(__TAURI_INVOKE("get_gitignore_template", { name })),
	/**
	 *  Detect project types by scanning for marker files in a directory.
	 * 
	 *  Returns all detected project types with recommended .gitignore templates.
	 */
	detectProjectType: (path: string) => typedError<ProjectDetection, GitError>(__TAURI_INVOKE("detect_project_type", { path })),
	/**  Write initialization files (.gitignore, README.md, etc.) to a directory. */
	writeInitFiles: (path: string, files: InitFile[]) => typedError<null, GitError>(__TAURI_INVOKE("write_init_files", { path, files })),
	/**
	 *  Fetch NuGet package information by package ID.
	 * 
	 *  Queries the NuGet Search API and Registration API, returning
	 *  combined package metadata.
	 */
	fetchNugetInfo: (packageId: string) => typedError<NugetPackageInfo, GitError>(__TAURI_INVOKE("fetch_nuget_info", { packageId })),
	/**
	 *  List files and directories at a given path within the repository.
	 * 
	 *  Merges entries from the HEAD tree and the working directory so that
	 *  uncommitted/untracked files are also visible in the browser.
	 *  Pass an empty string for `path` to list the root directory.
	 *  Returns directories first, then files, both sorted alphabetically.
	 */
	listRepoFiles: (path: string) => typedError<RepoFileEntry[], GitError>(__TAURI_INVOKE("list_repo_files", { path })),
	/**
	 *  Read file content from the repository at HEAD, with working-directory fallback.
	 * 
	 *  First tries the git HEAD tree. If the file is not found there (e.g. uncommitted),
	 *  falls back to reading from the working directory on disk.
	 *  Binary files are returned as base64-encoded content.
	 *  Text files are returned as UTF-8 strings.
	 */
	readRepoFile: (filePath: string) => typedError<RepoFileContent, GitError>(__TAURI_INVOKE("read_repo_file", { filePath })),
	/**  Get aggregated repository insights for a given time period. */
	getRepoInsights: (days: number) => typedError<RepoInsights, GitError>(__TAURI_INVOKE("get_repo_insights", { days })),
	/**  Get branch health information for all branches. */
	getBranchHealth: (staleDays: number) => typedError<BranchHealthInfo[], GitError>(__TAURI_INVOKE("get_branch_health", { staleDays })),
	/**
	 *  Read the user's global git configuration.
	 * 
	 *  Returns None for any value that is not set. Never errors —
	 *  if the config file cannot be opened, all fields are None.
	 */
	getGitGlobalConfig: () => typedError<GitGlobalConfig, GitError>(__TAURI_INVOKE("get_git_global_config")),
	/**
	 *  Set a value in the user's global git configuration.
	 * 
	 *  # Arguments
	 *  * `key` - The config key (e.g. "user.name", "user.email", "init.defaultBranch")
	 *  * `value` - The value to set
	 */
	setGitGlobalConfig: (key: string, value: string) => typedError<null, GitError>(__TAURI_INVOKE("set_git_global_config", { key, value })),
	/**
	 *  Discover extensions by scanning subdirectories for `flowforge.extension.json` manifests.
	 * 
	 *  - If the `extensions_dir` does not exist, returns an empty array (extensions are optional).
	 *  - Invalid manifests (bad JSON, missing required fields) are skipped with a warning log.
	 *  - Only truly unrecoverable I/O errors (e.g. permission denied on an existing directory)
	 *    return `Err`.
	 */
	discoverExtensions: (extensionsDir: string) => typedError<ExtensionManifest[], string>(__TAURI_INVOKE("discover_extensions", { extensionsDir })),
	/**
	 *  Fetch an extension manifest from a Git repository URL.
	 * 
	 *  Clones the repo to a temp directory, reads the manifest file,
	 *  and returns both the manifest JSON and the temp path for subsequent install.
	 */
	extensionFetchManifest: (gitUrl: string) => typedError<ExtensionFetchResult, string>(__TAURI_INVOKE("extension_fetch_manifest", { gitUrl })),
	/**
	 *  Install an extension from a previously fetched temp path.
	 * 
	 *  Moves the cloned repository to the extensions directory under
	 *  the extension's ID extracted from the manifest.
	 */
	extensionInstall: (tempPath: string, extensionsDir: string) => typedError<null, string>(__TAURI_INVOKE("extension_install", { tempPath, extensionsDir })),
	/**  Uninstall an extension by removing its directory. */
	extensionUninstall: (extensionId: string, extensionsDir: string) => typedError<null, string>(__TAURI_INVOKE("extension_uninstall", { extensionId, extensionsDir })),
	/**  Cancel an in-progress extension install by cleaning up the temp directory. */
	extensionCancelInstall: (tempPath: string) => typedError<null, string>(__TAURI_INVOKE("extension_cancel_install", { tempPath })),
	/**
	 *  Initiate the GitHub OAuth Device Flow.
	 * 
	 *  Returns device_code, user_code, and verification_uri for the frontend
	 *  to display to the user. The user visits the URI and enters the code.
	 */
	githubStartDeviceFlow: (scopes: string[]) => typedError<DeviceFlowResponse, GitHubError>(__TAURI_INVOKE("github_start_device_flow", { scopes })),
	/**
	 *  Poll GitHub for authorization status (single attempt).
	 * 
	 *  This is NOT a loop -- the frontend controls polling via setTimeout
	 *  and calls this command once per interval. This avoids long-running
	 *  Tauri commands and gives the frontend full control over the UX.
	 * 
	 *  Returns `AuthResult` on success or specific error variants that
	 *  the frontend uses for control flow:
	 *  - `AuthorizationPending`: user hasn't authorized yet, keep polling
	 *  - `SlowDown`: increase polling interval by 5 seconds
	 *  - `ExpiredToken`: device code expired, need to restart flow
	 *  - `AccessDenied`: user denied authorization
	 */
	githubPollAuth: (deviceCode: string, interval: number) => typedError<AuthResult, GitHubError>(__TAURI_INVOKE("github_poll_auth", { deviceCode, interval })),
	/**
	 *  Check if the user is authenticated and return their info.
	 *  Validates the stored token against the GitHub API.
	 *  If the token is invalid, auto-deletes it from the keychain.
	 */
	githubGetAuthStatus: () => typedError<AuthResult, GitHubError>(__TAURI_INVOKE("github_get_auth_status")),
	/**  Sign out by deleting the token from the OS keychain. */
	githubSignOut: () => typedError<null, GitHubError>(__TAURI_INVOKE("github_sign_out")),
	/**
	 *  Detect all GitHub remotes in the currently open repository.
	 * 
	 *  Opens the git repository from RepositoryState (same pattern as
	 *  existing git commands) and iterates all remotes, parsing each
	 *  URL to find GitHub repositories.
	 */
	githubDetectRemotes: () => typedError<GitHubRemoteInfo[], GitHubError>(__TAURI_INVOKE("github_detect_remotes")),
	/**
	 *  Check the current GitHub API rate limit for the authenticated user.
	 * 
	 *  Retrieves the token from the keychain and queries the GitHub
	 *  rate limit endpoint to return current usage information.
	 */
	githubCheckRateLimit: () => typedError<RateLimitInfo, GitHubError>(__TAURI_INVOKE("github_check_rate_limit")),
	/**
	 *  List pull requests for a repository with pagination.
	 * 
	 *  Returns a paginated list of pull request summaries sorted by
	 *  most recently updated. The `state` parameter can be "open",
	 *  "closed", or "all".
	 */
	githubListPullRequests: (owner: string, repo: string, state: string, page: number, perPage: number) => typedError<PullRequestListResponse, GitHubError>(__TAURI_INVOKE("github_list_pull_requests", { owner, repo, state, page, perPage })),
	/**
	 *  Fetch full details for a single pull request including comments.
	 * 
	 *  Makes two API calls: one for the PR detail and one for
	 *  the issue comments (which includes general discussion comments).
	 */
	githubGetPullRequest: (owner: string, repo: string, number: number) => typedError<PullRequestDetail, GitHubError>(__TAURI_INVOKE("github_get_pull_request", { owner, repo, number })),
	/**
	 *  List issues for a repository with pagination.
	 * 
	 *  Returns a paginated list of issue summaries sorted by most recently
	 *  updated. Pull requests are filtered out (GitHub's issues API returns
	 *  both issues and PRs). The `state` parameter can be "open", "closed",
	 *  or "all".
	 */
	githubListIssues: (owner: string, repo: string, state: string, page: number, perPage: number) => typedError<IssueListResponse, GitHubError>(__TAURI_INVOKE("github_list_issues", { owner, repo, state, page, perPage })),
	/**
	 *  Fetch full details for a single issue including comments.
	 * 
	 *  Makes two API calls: one for the issue detail and one for
	 *  all comments on the issue.
	 */
	githubGetIssue: (owner: string, repo: string, number: number) => typedError<IssueDetail, GitHubError>(__TAURI_INVOKE("github_get_issue", { owner, repo, number })),
	/**
	 *  Merge a pull request with a specified merge strategy.
	 * 
	 *  Calls the GitHub REST API PUT endpoint for merging.
	 *  Supports merge commit, squash, and rebase strategies.
	 */
	githubMergePullRequest: (owner: string, repo: string, pullNumber: number, mergeMethod: string, commitTitle: string | null, commitMessage: string | null, sha: string | null) => typedError<MergePullRequestResult, GitHubError>(__TAURI_INVOKE("github_merge_pull_request", { owner, repo, pullNumber, mergeMethod, commitTitle, commitMessage, sha })),
	/**
	 *  Create a new pull request.
	 * 
	 *  Creates a PR from the specified head branch to the base branch.
	 *  Optionally creates it as a draft.
	 */
	githubCreatePullRequest: (owner: string, repo: string, title: string, head: string, base: string, body: string | null, draft: boolean | null) => typedError<CreatePullRequestResult, GitHubError>(__TAURI_INVOKE("github_create_pull_request", { owner, repo, title, head, base, body, draft })),
	/**
	 *  Get branch information for pre-filling the Create PR form.
	 * 
	 *  Reads the current branch, detects the default base (main/master),
	 *  generates a title from the branch name, and collects commit
	 *  messages ahead of the base branch.
	 */
	githubGetBranchInfoForPr: () => typedError<BranchInfoForPr, GitHubError>(__TAURI_INVOKE("github_get_branch_info_for_pr")),
	/**
	 *  Quick health check for a repository by path.
	 *  Opens a temporary repo handle — does NOT affect the active repository.
	 *  Returns status (clean/dirty/ahead/behind/diverged/unknown), branch name, and ahead/behind counts.
	 */
	getRepoHealthQuick: (path: string) => typedError<RepoHealth, GitError>(__TAURI_INVOKE("get_repo_health_quick", { path })),
	/**
	 *  Open the user's configured terminal at the given path.
	 *  Spawns the terminal application with platform-specific handling.
	 */
	openInTerminal: (path: string, terminal: string) => typedError<null, GitError>(__TAURI_INVOKE("open_in_terminal", { path, terminal })),
};

/* Types */
/**  Information about active Gitflow workflow. */
export type ActiveFlow = {
	flowType: FlowType,
	name: string,
	sourceBranch: string,
};

/**  How many commits a local branch is ahead/behind its upstream. */
export type AheadBehind = {
	/**  Commits on local not yet on upstream */
	ahead: number,
	/**  Commits on upstream not yet on local */
	behind: number,
};

/**
 *  Result of an authentication check or successful auth flow.
 *  NEVER contains the actual token -- only metadata about the
 *  authenticated user. The token stays in Rust/keychain.
 */
export type AuthResult = {
	authenticated: boolean,
	username: string | null,
	avatarUrl: string | null,
	scopes: string[],
};

/**  Result of a batch branch deletion operation. */
export type BatchDeleteResult = {
	/**  Per-branch results */
	results: BranchDeleteResult[],
	/**  Count of successfully deleted branches */
	totalDeleted: number,
	/**  Count of branches that failed to delete */
	totalFailed: number,
};

/**  Result of deleting a single branch in a batch operation. */
export type BranchDeleteResult = {
	/**  Branch name that was targeted */
	name: string,
	/**  Whether the branch was successfully deleted */
	deleted: boolean,
	/**  Error message if deletion failed */
	error: string | null,
};

/**  Branch health information for the insights dashboard. */
export type BranchHealthInfo = {
	/**  Branch name */
	name: string,
	/**  Whether this is the current HEAD branch */
	isHead: boolean,
	/**  Whether this is a remote tracking branch */
	isRemote: boolean,
	/**  Date of last commit in YYYY-MM-DD format */
	lastCommitDate: string,
	/**  Timestamp of last commit in milliseconds */
	lastCommitTimestampMs: number,
	/**  Summary of the last commit message */
	lastCommitMessage: string,
	/**  Commits ahead of HEAD */
	ahead: number,
	/**  Commits behind HEAD */
	behind: number,
	/**  Whether the branch is stale (no commits within stale_days) */
	isStale: boolean,
	/**  Whether the branch is merged into HEAD (None if IS head) */
	isMerged: boolean | null,
};

/**  Information about a branch (local or remote). */
export type BranchInfo = {
	/**  Branch name (e.g., "main", "feature/login", "origin/feature/x") */
	name: string,
	/**  True if this is the currently checked out branch */
	isHead: boolean,
	/**  Short OID of the branch tip commit (7 chars) */
	lastCommitOid: string,
	/**  Summary line of the tip commit */
	lastCommitMessage: string,
	/**  Whether branch is merged into HEAD (None if IS head) */
	isMerged: boolean | null,
	/**  True for remote tracking branches, false for local */
	isRemote: boolean,
	/**  Remote name (e.g., "origin") for remote branches, None for local */
	remoteName: string | null,
};

/**  Branch information for pre-filling the Create PR form. */
export type BranchInfoForPr = {
	currentBranch: string,
	defaultBase: string,
	suggestedTitle: string,
	commitMessages: string[],
};

/**  Branch type classification for Gitflow-based coloring. */
export type BranchType = 
/**  Main/master branch - stable production code */
"main" | 
/**  Develop branch - integration branch for features */
"develop" | 
/**  Feature branches - new features in development */
"feature" | 
/**  Release branches - preparing for production release */
"release" | 
/**  Hotfix branches - urgent production fixes */
"hotfix" | 
/**  Other branches that don't follow Gitflow naming */
"other";

/**  A commit entry for the changelog. */
export type ChangelogCommit = {
	/**  Short commit hash. */
	hash: string,
	/**  Commit scope (optional). */
	scope: string | null,
	/**  Commit description. */
	description: string,
	/**  Whether this is a breaking change. */
	breaking: boolean,
	/**  Commit author name. */
	author: string,
	/**  Commit date in ISO format. */
	date: string,
};

/**  Output from changelog generation. */
export type ChangelogOutput = {
	/**  Rendered markdown changelog. */
	markdown: string,
	/**  Total number of commits included. */
	commitCount: number,
	/**  Commits grouped by type. */
	groups: CommitGroup[],
};

/**
 *  Progress events for clone operations.
 * 
 *  Uses tagged enum serialization for frontend type safety.
 */
export type CloneProgress = 
/**  Clone operation started */
{ event: "started"; data: {
	url: string,
} } | 
/**  Receiving objects from remote */
{ event: "receiving"; data: {
	received: number,
	total: number,
	bytes: number,
} } | 
/**  Resolving deltas */
{ event: "resolving"; data: {
	current: number,
	total: number,
} } | 
/**  Checking out files */
{ event: "checkout"; data: {
	current: number,
	total: number,
	path: string,
} } | 
/**  Clone completed successfully */
{ event: "finished"; data: {
	path: string,
} };

/**  Comment info for frontend display. */
export type CommentInfo = {
	id: string,
	authorLogin: string,
	authorAvatarUrl: string,
	body: string,
	createdAt: string,
	updatedAt: string,
	htmlUrl: string,
};

/**  Full details of a commit. */
export type CommitDetails = {
	oid: string,
	shortOid: string,
	message: string,
	authorName: string,
	authorEmail: string,
	/**  Unix timestamp in milliseconds (safe for JS Number) */
	authorTimestampMs: number,
	committerName: string,
	committerEmail: string,
	/**  Unix timestamp in milliseconds (safe for JS Number) */
	committerTimestampMs: number,
	parentOids: string[],
	filesChanged: FileChanged[],
};

/**  Complete commit graph with nodes and edges for visualization. */
export type CommitGraph = {
	/**  All commit nodes in topological order */
	nodes: GraphNode[],
	/**  Edges representing parent-child relationships */
	edges: GraphEdge[],
};

/**  A group of commits by type. */
export type CommitGroup = {
	/**  Commit type (e.g., "feat", "fix"). */
	commitType: string,
	/**  Display title (e.g., "Features", "Bug Fixes"). */
	title: string,
	/**  Emoji for the commit type (e.g., sparkles for feat). */
	emoji: string,
	/**  Commits in this group. */
	commits: ChangelogCommit[],
};

/**
 *  Information about a created commit.
 * 
 *  Returned after successful commit creation to confirm
 *  the commit was made and provide its identifiers.
 */
export type CommitInfo = {
	/**  Full commit OID (40 hex characters) */
	oid: string,
	/**  Short commit OID (7 characters) */
	shortOid: string,
	/**  Commit message */
	message: string,
};

/**  Summary of a commit for list display. */
export type CommitSummary = {
	oid: string,
	shortOid: string,
	messageSubject: string,
	authorName: string,
	authorEmail: string,
	/**  Unix timestamp in milliseconds (safe for JS Number up to year 275760) */
	timestampMs: number,
};

/**  Commit type enumeration. */
export type CommitType = "feat" | "fix" | "docs" | "style" | "refactor" | "perf" | "test" | "chore" | "ci" | "build" | "revert";

/**  Confidence level for type inference. */
export type Confidence = "high" | "medium" | "low";

/**  Content from all three sides of a merge conflict. */
export type ConflictContent = {
	/**  Path of the conflicted file (relative to repo root) */
	path: string,
	/**  Content from the "ours" side (current branch / HEAD) */
	ours: string | null,
	/**  Content from the "theirs" side (incoming branch) */
	theirs: string | null,
	/**  Content from the common ancestor (base) */
	base: string | null,
	/**  Label for the "ours" side (e.g., "main" or "HEAD") */
	oursName: string,
	/**  Label for the "theirs" side (e.g., "feature/xyz") */
	theirsName: string,
};

/**  Contributor statistics aggregated from commit history. */
export type ContributorStats = {
	/**  Author name */
	name: string,
	/**  Author email */
	email: string,
	/**  Total number of commits by this contributor */
	commitCount: number,
	/**  Percentage of total commits */
	percentage: number,
	/**  Timestamp of first commit in milliseconds */
	firstCommitMs: number,
	/**  Timestamp of last commit in milliseconds */
	lastCommitMs: number,
};

/**  Result of creating a pull request. */
export type CreatePullRequestResult = {
	number: number,
	htmlUrl: string,
	title: string,
	state: string,
};

/**  Options for creating a new worktree. */
export type CreateWorktreeOptions = {
	/**  Name for the worktree */
	name: string,
	/**  Path where the worktree will be created */
	path: string,
	/**  Branch to checkout (None for detached HEAD at current commit) */
	branch: string | null,
	/**  If true and branch is Some, create a new branch with that name */
	createBranch: boolean,
};

/**  Daily commit count for a specific date. */
export type DailyCommitCount = {
	/**  Date in YYYY-MM-DD format */
	date: string,
	/**  Number of commits on this date */
	count: number,
};

export type DetectedProject = {
	projectType: string,
	markerFile: string,
	recommendedTemplates: string[],
};

/**
 *  Response from GitHub's device code endpoint.
 *  Returned to the frontend so it can display the user_code
 *  and verification_uri to the user.
 */
export type DeviceFlowResponse = {
	deviceCode: string,
	userCode: string,
	verificationUri: string,
	expiresIn: number,
	interval: number,
};

/**  A single diff hunk with line range information. */
export type DiffHunk = {
	oldStart: number,
	oldLines: number,
	newStart: number,
	newLines: number,
	header: string,
};

/**  Enhanced diff hunk with per-line detail for interactive staging. */
export type DiffHunkDetail = {
	index: number,
	oldStart: number,
	oldLines: number,
	newStart: number,
	newLines: number,
	header: string,
	lines: DiffLine[],
};

/**  A single line in a diff hunk with origin and line numbers. */
export type DiffLine = {
	origin: DiffLineOrigin,
	oldLineno: number | null,
	newLineno: number | null,
	content: string,
};

/**  Origin type of a diff line. */
export type DiffLineOrigin = "context" | "addition" | "deletion";

/**  A blade type contributed by an extension. */
export type ExtensionBladeContribution = {
	/**  The blade type identifier (used as the `type` field in navigation). */
	type: string,
	/**  Display title for the blade. */
	title: string,
	/**  Whether only one instance of this blade can be open at a time. */
	singleton: boolean | null,
};

/**  A command contributed by an extension. */
export type ExtensionCommandContribution = {
	/**  Unique command identifier. */
	id: string,
	/**  Display title for the command (shown in command palette). */
	title: string,
	/**  Optional category for grouping in the command palette. */
	category: string | null,
};

/**  Contribution points an extension can register. */
export type ExtensionContributes = {
	/**  Blade types contributed by this extension. */
	blades: ExtensionBladeContribution[] | null,
	/**  Commands contributed by this extension. */
	commands: ExtensionCommandContribution[] | null,
	/**  Toolbar actions contributed by this extension. */
	toolbar: ExtensionToolbarContribution[] | null,
};

/**  Result of fetching an extension manifest from a Git URL. */
export type ExtensionFetchResult = {
	manifestJson: string,
	tempPath: string,
};

/**
 *  Extension manifest parsed from `flowforge.extension.json`.
 * 
 *  Matches the JSON schema that extensions ship alongside their entry point.
 *  All field names use camelCase in JSON via the `rename_all` attribute.
 */
export type ExtensionManifest = {
	/**  Unique identifier for the extension (e.g. "github"). */
	id: string,
	/**  Human-readable display name. */
	name: string,
	/**  Semantic version of the extension (e.g. "1.0.0"). */
	version: string,
	/**  Optional longer description of what the extension does. */
	description: string | null,
	/**  API version the extension targets (e.g. "1"). */
	apiVersion: string,
	/**  Relative path to the JavaScript entry point (e.g. "index.js"). */
	main: string,
	/**  Contributions the extension registers (blades, commands, toolbar items). */
	contributes: ExtensionContributes | null,
	/**  Permissions the extension requests (e.g. ["fs:read", "network"]). */
	permissions: string[] | null,
	/**
	 *  Absolute path to the extension directory on disk.
	 *  Populated by discovery after parsing — not present in the JSON file.
	 */
	basePath?: string | null,
	/**
	 *  Trust level for the extension.
	 *  "built-in" for bundled extensions, "user-trusted" for user-installed,
	 *  "sandboxed" for untrusted third-party (future).
	 *  Defaults to "sandboxed" when not specified in the manifest JSON.
	 */
	trustLevel?: string,
};

/**  A toolbar action contributed by an extension. */
export type ExtensionToolbarContribution = {
	/**  Unique toolbar action identifier. */
	id: string,
	/**  Display label for the toolbar action. */
	label: string,
	/**  Toolbar group to place the action in (e.g. "vcs", "tools"). */
	group: string | null,
	/**  Sort priority within the group (lower values appear first). */
	priority: number | null,
};

/**  A single file change with its status and optional diff stats. */
export type FileChange = {
	path: string,
	status: FileStatus,
	additions: number | null,
	deletions: number | null,
};

/**  A file changed in a commit. */
export type FileChanged = {
	path: string,
	status: string,
	additions: number,
	deletions: number,
};

/**  Complete file diff with old/new content for Monaco DiffEditor. */
export type FileDiff = {
	path: string,
	oldContent: string,
	newContent: string,
	hunks: DiffHunk[],
	isBinary: boolean,
	language: string,
};

/**  Status of a file in the working directory or index. */
export type FileStatus = "modified" | "added" | "deleted" | { renamed: {
	old_path: string,
} } | "untracked" | "conflicted";

/**  Flow type for active workflow. */
export type FlowType = "feature" | "release" | "hotfix";

/**
 *  Git operation errors that serialize across the IPC boundary.
 * 
 *  These errors are sent to the frontend as typed objects,
 *  allowing proper error handling in TypeScript.
 */
export type GitError = { type: "NotFound"; message: string } | { type: "NotARepository"; message: string } | { type: "EmptyRepository" } | { type: "StatusError"; message: string } | { type: "OperationFailed"; message: string } | { type: "PathNotFound"; message: string } | { type: "Internal"; message: string } | { type: "NoStagedChanges" } | { type: "SignatureError"; message: string } | { type: "RemoteNotFound"; message: string } | { type: "AuthenticationFailed"; message: string } | { type: "PushRejected"; message: string } | { type: "NetworkError"; message: string } | { type: "BranchNotFound"; message: string } | { type: "CannotDeleteCurrentBranch" } | { type: "BranchNotMerged"; message: string } | { type: "InvalidBranchName"; message: string } | { type: "BranchAlreadyExists"; message: string } | { type: "DirtyWorkingDirectory" } | { type: "CheckoutWouldOverwrite"; message: string } | { type: "StashNotFound"; message: number } | { type: "NothingToStash" } | { type: "TagAlreadyExists"; message: string } | { type: "TagNotFound"; message: string } | { type: "NoMergeInProgress" } | { type: "FileNotConflicted"; message: string } | { type: "InvalidUrl"; message: string } | { type: "PathExists"; message: string } | { type: "CloneFailed"; message: string } | { type: "InvalidPath"; message: string } | { type: "HunkIndexOutOfRange"; message: number } | { type: "LineRangeInvalid"; message: string } | { type: "BinaryPartialStaging" };

/**  Snapshot of relevant global git configuration values. */
export type GitGlobalConfig = {
	/**  user.name from global config, or None if unset. */
	userName: string | null,
	/**  user.email from global config, or None if unset. */
	userEmail: string | null,
	/**  init.defaultBranch from global config, or None if unset. */
	defaultBranch: string | null,
};

/**
 *  GitHub operation errors that serialize across the IPC boundary.
 * 
 *  These errors are sent to the frontend as typed objects,
 *  allowing proper error handling in TypeScript. The frontend
 *  checks `err.type` to decide control flow (e.g., continue polling
 *  on `AuthorizationPending`, increase interval on `SlowDown`).
 */
export type GitHubError = { type: "OAuthFailed"; message: string } | { type: "AuthorizationPending" } | { type: "AccessDenied" } | { type: "ExpiredToken" } | { type: "SlowDown" } | { type: "KeychainError"; message: string } | { type: "NetworkError"; message: string } | { type: "NotAuthenticated" } | { type: "RateLimitExceeded"; message: string } | { type: "Internal"; message: string } | { type: "Cancelled" } | { type: "ApiError"; message: string } | { type: "NotFound"; message: string } | { type: "Forbidden"; message: string } | { type: "MergeNotAllowed"; message: string } | { type: "HeadChanged"; message: string } | { type: "ValidationFailed"; message: string };

/**  Information about a detected GitHub remote in the current repository. */
export type GitHubRemoteInfo = {
	remoteName: string,
	owner: string,
	repo: string,
	url: string,
};

/**  Configuration for Gitflow initialization. */
export type GitflowConfig = {
	/**  Main/production branch name (e.g., "main" or "master") */
	mainBranch: string,
	/**  Development branch name (e.g., "develop") */
	developBranch: string,
	/**  Prefix for feature branches (e.g., "feature/") */
	featurePrefix: string,
	/**  Prefix for release branches (e.g., "release/") */
	releasePrefix: string,
	/**  Prefix for hotfix branches (e.g., "hotfix/") */
	hotfixPrefix: string,
};

/**  Context about the repository's Gitflow state. */
export type GitflowContext = {
	/**  Current Gitflow state derived from branch name */
	state: GitflowState,
	/**  Current branch name */
	currentBranch: string,
	/**  Whether the repository has a main/master branch */
	hasMain: boolean,
	/**  Whether the repository has a develop branch */
	hasDevelop: boolean,
	/**  Whether the repository has Gitflow initialized (config in .git/config) */
	isInitialized: boolean,
};

/**  Gitflow operation errors that serialize across the IPC boundary. */
export type GitflowError = 
/**  Wrong branch context for the requested operation */
{ type: "InvalidContext"; data: {
	expected: string,
	actual: string,
} } | 
/**  Operation requires being on a feature branch */
{ type: "NotOnFeatureBranch" } | 
/**  Operation requires being on a release branch */
{ type: "NotOnReleaseBranch" } | 
/**  Operation requires being on a hotfix branch */
{ type: "NotOnHotfixBranch" } | 
/**  A release is already in progress */
{ type: "ReleaseInProgress"; data: string } | 
/**  A hotfix is already in progress */
{ type: "HotfixInProgress"; data: string } | 
/**  Merge conflicts encountered during finish operation */
{ type: "MergeConflict" } | 
/**  Working directory has uncommitted changes */
{ type: "DirtyWorkingTree" } | 
/**
 *  Switching to the named branch would overwrite uncommitted local changes.
 *  The checkout is refused and nothing is modified.
 */
{ type: "CheckoutWouldOverwriteChanges"; data: string } | 
/**  Repository has no commits yet */
{ type: "UnbornHead" } | 
/**  Specified branch was not found */
{ type: "BranchNotFound"; data: string } | 
/**  Branch already exists */
{ type: "BranchExists"; data: string } | 
/**  Repository is not configured for Gitflow (missing main or develop) */
{ type: "NotGitflowRepo" } | 
/**  Invalid branch name for Gitflow */
{ type: "InvalidBranchName"; data: string } | 
/**  Wrapped git2 error */
{ type: "Git"; data: string };

/**  Result of Gitflow initialization. */
export type GitflowInitResult = {
	/**  Whether the develop branch was created (false if it already existed) */
	developCreated: boolean,
	/**
	 *  Whether HEAD was moved to the develop branch (false if it was already
	 *  checked out, in which case the working tree was not touched)
	 */
	switchedToDevelop: boolean,
};

/**  The current state of the Gitflow workflow. */
export type GitflowState = 
/**  No active workflow (on main, develop, or other) */
{ type: "Idle" } | 
/**  Working on a feature branch */
{ type: "Feature"; data: {
	name: string,
} } | 
/**  Working on a release branch */
{ type: "Release"; data: {
	version: string,
} } | 
/**  Working on a hotfix branch */
{ type: "Hotfix"; data: {
	name: string,
} };

/**  Status of Gitflow operations for UI consumption. */
export type GitflowStatus = {
	currentBranch: string,
	isGitflowReady: boolean,
	canStartFeature: boolean,
	canFinishFeature: boolean,
	canStartRelease: boolean,
	canFinishRelease: boolean,
	canStartHotfix: boolean,
	canFinishHotfix: boolean,
	canAbort: boolean,
	activeFlow: ActiveFlow | null,
	/**  Context about the repository's Gitflow state */
	context: GitflowContext,
};

export type GitignoreTemplate = {
	name: string,
	content: string,
	source: string,
};

export type GitignoreTemplateList = {
	templates: GitignoreTemplateName[],
	source: string,
};

export type GitignoreTemplateName = {
	name: string,
	category: string,
};

/**  An edge in the commit graph connecting parent and child commits. */
export type GraphEdge = {
	/**  SHA of the child commit (the commit that has this parent) */
	from: string,
	/**  SHA of the parent commit */
	to: string,
};

/**  A node in the commit graph representing a single commit. */
export type GraphNode = {
	/**  Full SHA-1 hash of the commit (40 chars) */
	oid: string,
	/**  Short SHA-1 hash of the commit (7 chars) */
	shortOid: string,
	/**  First line of the commit message */
	message: string,
	/**  Author name */
	author: string,
	/**  Unix timestamp in milliseconds (safe for JS Number up to year 275760) */
	timestampMs: number,
	/**  Parent commit SHAs */
	parents: string[],
	/**  Classification of the branch type for coloring */
	branchType: BranchType,
	/**  Branch names pointing to this commit */
	branchNames: string[],
	/**  Whether this commit is a first-parent ancestor of HEAD */
	isHeadAncestor: boolean,
	/**  The "ideological branch" name that owns this commit for coloring */
	ideologicalBranch: string,
};

export type InitFile = {
	filename: string,
	content: string,
};

/**  Result of a successful git init operation. */
export type InitResult = {
	/**  Absolute path to the initialized repository. */
	repoPath: string,
	/**  Name of the initial branch (e.g. "main"). */
	initialBranch: string,
};

/**  Full issue detail with body, assignees, milestone, and comments. */
export type IssueDetail = {
	number: number,
	title: string,
	state: string,
	authorLogin: string,
	authorAvatarUrl: string,
	labels: LabelInfo[],
	assignees: UserInfo[],
	milestone: MilestoneInfo | null,
	body: string,
	createdAt: string,
	updatedAt: string,
	closedAt: string | null,
	htmlUrl: string,
	commentCount: number,
	comments: CommentInfo[],
};

/**  Paginated list of issue summaries. */
export type IssueListResponse = {
	items: IssueSummary[],
	hasNextPage: boolean,
	nextPage: number | null,
};

/**  Summary of an issue for list views. */
export type IssueSummary = {
	number: number,
	title: string,
	state: string,
	authorLogin: string,
	authorAvatarUrl: string,
	labels: LabelInfo[],
	assigneeLogins: string[],
	milestoneTitle: string | null,
	createdAt: string,
	updatedAt: string,
	htmlUrl: string,
	commentCount: number,
};

/**  Label info for frontend display. */
export type LabelInfo = {
	name: string,
	color: string,
	description: string | null,
};

/**
 *  Last commit message with subject and body parsed separately.
 * 
 *  Used for amend commit pre-fill functionality.
 */
export type LastCommitMessage = {
	/**  First line of the commit message */
	subject: string,
	/**  Everything after the first blank line (if exists) */
	body: string | null,
	/**  Full commit message */
	fullMessage: string,
};

/**  A contiguous range of lines for partial staging operations. */
export type LineRange = {
	start: number,
	end: number,
	/**
	 *  Optional coordinate-space tag disambiguating additions from deletions.
	 * 
	 *  When `None` (the legacy behaviour), the range is matched against both the
	 *  new-file line number of additions and the old-file line number of deletions,
	 *  which can mis-stage an unrelated change that happens to share a line number.
	 *  When `Some`, only lines of the matching kind in the requested range are
	 *  affected, eliminating the cross-coordinate collision.
	 */
	kind?: LineRangeKind | null,
};

/**
 *  Which diff coordinate space a [`LineRange`] refers to.
 * 
 *  Additions are identified by their *new-file* line number, while deletions are
 *  identified by their *old-file* line number. These live in different coordinate
 *  spaces, so a single numeric range is ambiguous: an addition at new-line N and an
 *  unrelated deletion at old-line N would both match. Tagging a range with its kind
 *  removes that ambiguity so only the lines the user actually selected are (un)staged.
 */
export type LineRangeKind = 
/**  The range selects addition lines, keyed by their new-file line number. */
"addition" | 
/**  The range selects deletion lines, keyed by their old-file line number. */
"deletion";

/**  Result of merge analysis. */
export type MergeAnalysisResult = 
/**  Already merged, nothing to do */
"upToDate" | 
/**  Can fast-forward without merge commit */
"fastForward" | 
/**  Requires merge commit */
"normal" | 
/**  HEAD doesn't exist yet */
"unborn";

/**  Result of merging a pull request. */
export type MergePullRequestResult = {
	merged: boolean,
	sha: string | null,
	message: string,
};

/**  Result of a merge operation. */
export type MergeResult = {
	/**  Whether the merge was successful */
	success: boolean,
	/**  Analysis result (what type of merge was performed) */
	analysis: MergeAnalysisResult,
	/**  OID of merge commit (if created) */
	commitOid: string | null,
	/**  True if fast-forward was used */
	fastForwarded: boolean,
	/**  True if conflicts remain */
	hasConflicts: boolean,
	/**  List of conflicted file paths */
	conflictedFiles: string[],
};

/**  Status of an in-progress merge. */
export type MergeStatus = {
	/**  Whether a merge is currently in progress */
	inProgress: boolean,
	/**  List of conflicted file paths */
	conflictedFiles: string[],
};

/**  Milestone info for frontend display. */
export type MilestoneInfo = {
	number: number,
	title: string,
	state: string,
};

export type NugetPackageInfo = {
	id: string,
	version: string,
	description: string,
	authors: string,
	/**
	 *  Exported as a TypeScript `number`: Specta refuses to emit `u64` by
	 *  default (BigInt precision), but download counts fit comfortably in
	 *  `Number.MAX_SAFE_INTEGER`.
	 */
	totalDownloads: number,
	published: string,
	projectUrl: string | null,
	licenseUrl: string | null,
	tags: string[],
	nugetUrl: string,
};

export type ProjectDetection = {
	detectedTypes: DetectedProject[],
};

/**  Full pull request detail with body, stats, and comments. */
export type PullRequestDetail = {
	number: number,
	title: string,
	state: string,
	draft: boolean,
	merged: boolean,
	authorLogin: string,
	authorAvatarUrl: string,
	headRef: string,
	headSha: string,
	baseRef: string,
	labels: LabelInfo[],
	body: string,
	createdAt: string,
	updatedAt: string,
	htmlUrl: string,
	commentCount: number,
	reviewCommentCount: number,
	commits: number,
	additions: number,
	deletions: number,
	changedFiles: number,
	comments: CommentInfo[],
};

/**  Paginated list of pull request summaries. */
export type PullRequestListResponse = {
	items: PullRequestSummary[],
	hasNextPage: boolean,
	nextPage: number | null,
};

/**  Summary of a pull request for list views. */
export type PullRequestSummary = {
	number: number,
	title: string,
	state: string,
	draft: boolean,
	merged: boolean,
	authorLogin: string,
	authorAvatarUrl: string,
	headRef: string,
	baseRef: string,
	labels: LabelInfo[],
	createdAt: string,
	updatedAt: string,
	htmlUrl: string,
	commentCount: number,
};

/**  Rate limit information from the GitHub API. */
export type RateLimitInfo = {
	limit: number,
	remaining: number,
	reset: number,
	used: number,
};

/**  A recently checked-out branch extracted from the reflog. */
export type RecentCheckout = {
	/**  Branch name (bare, without refs/heads/ prefix) */
	name: string,
	/**  Unix timestamp in milliseconds when the checkout occurred */
	lastCheckoutMs: number,
};

/**  Information about a configured remote. */
export type RemoteInfo = {
	name: string,
	url: string,
};

/**  File content read from the repository at HEAD. */
export type RepoFileContent = {
	content: string,
	isBinary: boolean,
	size: number,
};

/**  A single entry in a repository directory listing. */
export type RepoFileEntry = {
	name: string,
	path: string,
	isDir: boolean,
	size: number,
};

/**
 *  Quick health check result for a repository.
 *  Used by the welcome screen to show status dots without affecting the active repo.
 */
export type RepoHealth = {
	status: string,
	branchName: string,
	ahead: number,
	behind: number,
	isDirty: boolean,
};

/**  Aggregated repository insights over a time period. */
export type RepoInsights = {
	/**  Total number of commits in the time period */
	totalCommits: number,
	/**  Number of active branches (local + remote) */
	activeBranches: number,
	/**  Number of unique contributors */
	contributorCount: number,
	/**  Timestamp of the earliest commit seen (milliseconds) */
	firstCommitMs: number,
	/**  Daily commit counts sorted by date ascending */
	dailyCommits: DailyCommitCount[],
	/**  Contributor statistics sorted by commit count descending */
	contributors: ContributorStats[],
};

/**
 *  Repository status information sent to frontend.
 * 
 *  This is a lightweight summary - we don't send raw git2 objects
 *  across the IPC boundary.
 */
export type RepoStatus = {
	/**  Current branch name (or short commit hash if detached) */
	branchName: string,
	/**  Whether the working directory has uncommitted changes */
	isDirty: boolean,
	/**  Absolute path to the repository root */
	repoPath: string,
	/**  Repository display name (folder name) */
	repoName: string,
};

/**  A scope suggestion from commit history. */
export type ScopeSuggestion = {
	/**  The scope string. */
	scope: string,
	/**  Number of times this scope has been used. */
	usageCount: number,
};

/**  Complete staging status showing staged, unstaged, and untracked files. */
export type StagingStatus = {
	staged: FileChange[],
	unstaged: FileChange[],
	untracked: FileChange[],
};

/**  A stash entry representing saved work. */
export type StashEntry = {
	/**  0-based index for stash operations */
	index: number,
	/**  Stash message */
	message: string,
	/**  Commit OID of the stash */
	oid: string,
};

/**
 *  Progress events for remote sync operations.
 *  Uses tagged enum serialization for frontend type safety.
 */
export type SyncProgress = { event: "started"; data: {
	operation: string,
} } | { event: "counting"; data: {
	current: number,
	total: number,
} } | { event: "compressing"; data: {
	current: number,
	total: number,
} } | { event: "transferring"; data: {
	current: number,
	total: number,
	bytes: number,
} } | { event: "resolving"; data: {
	current: number,
	total: number,
} } | { event: "finished"; data: {
	operation: string,
} } | { event: "error"; data: {
	message: string,
} };

/**
 *  Result of a sync operation (push/pull/fetch).
 * 
 *  Every field is derived from what the operation actually did, so the
 *  frontend can build self-contained feedback ("Pushed feature/x to origin,
 *  3 commits") without relying on possibly-stale UI state.
 */
export type SyncResult = {
	success: boolean,
	message: string,
	/**  Number of commits sent (push) or received (fetch/pull). */
	commitsTransferred: number,
	/**  Name of the remote the operation targeted. */
	remote: string,
	/**  Local branch involved (`None` for fetch, which touches no local branch). */
	branch: string | null,
	/**  Remote-tracking refs created or updated by a fetch/pull. */
	updatedRefs: number,
	/**  True when there was nothing to transfer. */
	upToDate: boolean,
	/**
	 *  True when this push configured `<remote>/<branch>` as the upstream
	 *  of the local branch (first push of a branch).
	 */
	upstreamSet: boolean,
};

/**  Information about a git tag. */
export type TagInfo = {
	/**  Tag name (e.g., "v1.0.0") */
	name: string,
	/**  OID of the tag object (for annotated) or target commit (for lightweight) */
	oid: string,
	/**  OID of the commit the tag points to */
	targetOid: string,
	/**  Tag message (None for lightweight tags) */
	message: string | null,
	/**  Tagger name (None for lightweight tags) */
	tagger: string | null,
	/**  True for annotated tags, false for lightweight */
	isAnnotated: boolean,
	/**  Creation timestamp in milliseconds since epoch */
	createdAtMs: number,
};

/**  A suggested commit type based on file analysis. */
export type TypeSuggestion = {
	/**  The suggested commit type. */
	suggestedType: CommitType,
	/**  Confidence level of the suggestion. */
	confidence: Confidence,
	/**  Reason for the suggestion. */
	reason: string,
};

/**  Information about what can be undone */
export type UndoInfo = {
	/**  Whether undo is available */
	canUndo: boolean,
	/**  Description of what will be undone */
	description: string | null,
	/**  The reflog entry message */
	reflogMessage: string | null,
	/**  The commit OID to revert to */
	targetOid: string | null,
};

/**  Minimal user info for frontend display. */
export type UserInfo = {
	login: string,
	avatarUrl: string,
};

/**  A validation error. */
export type ValidationError = {
	/**  Error code for programmatic handling. */
	code: string,
	/**  Human-readable error message. */
	message: string,
	/**  Optional suggestion for fixing the error. */
	suggestion: string | null,
};

/**  Result of validating a commit message. */
export type ValidationResult = {
	/**  Whether the message is valid. */
	isValid: boolean,
	/**  Validation errors (if any). */
	errors: ValidationError[],
	/**  Validation warnings (if any). */
	warnings: ValidationWarning[],
};

/**  A validation warning. */
export type ValidationWarning = {
	/**  Warning code for programmatic handling. */
	code: string,
	/**  Human-readable warning message. */
	message: string,
};

/**  Information about a git worktree. */
export type WorktreeInfo = {
	/**  Worktree name (for linked worktrees) or "main" for the main worktree */
	name: string,
	/**  Absolute path to the worktree directory */
	path: string,
	/**  Branch checked out in this worktree (None if detached HEAD) */
	branch: string | null,
	/**  Current status of the worktree */
	status: WorktreeStatus,
	/**  True if this is the main worktree (not a linked worktree) */
	isMain: boolean,
	/**  True if the worktree is locked */
	isLocked: boolean,
};

/**  Status of a worktree's working directory. */
export type WorktreeStatus = 
/**  No uncommitted changes */
"clean" | 
/**  Has uncommitted changes */
"dirty" | 
/**  Has unresolved merge conflicts */
"conflicts" | 
/**  Worktree is invalid or corrupted */
"invalid";

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

